FROM php:7.0-cli

COPY --from=composer:2.2 /usr/bin/composer /usr/bin/composer
RUN echo "deb http://archive.debian.org/debian/ stretch main" > /etc/apt/sources.list \
    && echo "deb http://archive.debian.org/debian-security stretch/updates main" >> /etc/apt/sources.list \
    && apt-get -y update \
    && apt-get -y install zip unzip 